---
- name: Deploy app to VPS
  hosts: vps
  become: yes
  tasks:
    - name: Pull Docker image
      docker_image:
        name: olyfaneva/front-end
        tag: latest
        source: pull

    - name: Stop old container if running
      docker_container:
        name: front
        image: olyfaneva/front-end:latest   # Ajout de l'image ici
        state: stopped
        restart_policy: no

    - name: Remove old container
      docker_container:
        name: front
        state: absent

    - name: Run new container
      docker_container:
        name: front-end
        image: olyfaneva/front-end:latest
        state: started
        restart_policy: always
        ports:
          - "3003:3000"
